<?php
session_start();
if(isset($_SESSION['userID'])){
	unset($_SESSION['userID']);
}
if(isset($_SESSION['admin'])){
	unset($_SESSION['admin']);
}
session_unset();
session_destroy();
header("Location:index.php");
?>